### ISSUE TITLE
Change repository name

### ISSUE THREAD

**Issue by thclark** [windpioneers/VAP-SummarySheet#1]
### What is the current behavior?

The repository name is `VAP-SummarySheet`. Our repository naming convention uses `kebab-case` so we don't have to check the casing when we're typing repos.

### What is the expected behavior?

It should be `vap-summary-sheet`

**Comment by rgeet13** [comment]
Changed the name of the repo to wind park-summary-script as they(wind engineers) have given the name of windpark to the summary sheet it generates.
